#!/usr/bin/env bash
# DNS records for specified subdomains of a domain

function subdom {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
        destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $5 }')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

subdom "$1" "$2"
