#!/usr/bin/env bash
# shellcheck

# function to query 
configEya() {
    local subdomain="$1"
    local domain="$2"

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n +2 | awk -v subdomain="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", subdomain, $4, $5}'
}

args="$#"
if [[ "$args" -eq 1 ]]; then
    configEya www "$1"
    configEya lb-01 "$1"
    configEya web-01 "$1"
    configEya web-02 "$1"
elif [[ "$args" -eq 2 ]]; then
	domain="$1"
	subdomain="$2"
    
	dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n +2 | awk -v subdomain="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", subdomain, $4, $5}'
else
	exit 1
fi
