#!/usr/bin/env bash
# script

sudo apt update

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo nginx -t

sudo service nginx restart
