#!/usr/bin/env bash
# script

supt-get update -y
sudo apt-get install -y nginx
# configure Nginx
ufw allow 'Nginx HTTP'
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
sudo service nginx restart
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/nulldo apt update
