#!/usr/bin/env bash
# configure nginx

sudo apt-get -y update
sudo apt-get -y install nginx

sudo rm -f /var/www/html/*
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start

NGINX_CONFIG="
server {
       listen 80 default_server;
       listen [::]:80 default_server;

       root /var/www/html;

	   add_header X-Served-By \$hostname;

       index index.html index.htm index.nginx-debian.html;

       server_name _;

       location /redirect_me {
       			return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	   }

       location / {
       			try_files \$uri \$uri/ =404;
       }
}
"

echo -e "$NGINX_CONFIG" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx reload
