#!/usr/bin/env bash
# configure nginx

apt-get update
sudo apt install net-tools
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default


NGINX_CONFIG="
server {
       listen 80 default_server;
       listen [::]:80 default_server;

       root /var/www/html;

	   add_header X-Served-By \$hostname;

       index index.html index.htm index.nginx-debian.html;

       server_name _;

       location /redirect_me {
       			return 301  https://www.youtube.com/watch?v=QH2-TGUlwu4;
	   }

       location / {
       			try_files \$uri \$uri/ =404;
       }
}
"

echo -e "$NGINX_CONFIG" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx reload
