#!/usr/bin/env bash
# configure and Install HAproxy as a load balancer

sudo apt-get update
sudo apt-get -y install haproxy

config="
frontend default
    bind 0.0.0.0:80
    acl use1 req.hdr(X-Served-by) -i 425254-web-01
    acl use2 req.hdr(X-Served-by) -i 425254-web-02
    use_backend web1 if use1
    use_backend web2 if use2
    default_backend all

backend web1
    server 425254-web-01 54.82.132.222:80

backend web2
    server 425254-web-02 52.91.148.76:80

backend all
    server 425254-web-01 54.82.132.222:80
    server 425254-web-02 52.91.148.76:80
"

echo "${config}" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
