#!/usr/bin/env bash
# Configuring Nginx

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 425254-web-01 52.91.154.49 check
    server 425254-web-02 54.197.206.197 check
"

apt-get -y update
apt-get -y upgrade

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
