#!/usr/bin/env bash
#displays a list of currently running processes
#all processes, for all users, including those which might not have a TTY
#Display in a user-oriented format
#Show process hierarchiy

ps -aux --forest
