#!/usr/bin/env bash
#processes, need to be managed.
#instructions is: start, restart and stop.
#The most popular way of doing so on Unix system is to use the init scripts.

checker="$1"

if [ -z "$checker" ]; then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit
fi

if [ "$checker" == "start" ]; then

  bash ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$checker" == "stop" ]; then
  [ -e "/var/run/my_process.pid" ] && pkill -f './manage_my_process' && rm /var/run/my_process.pid
  echo "manage_my_process stopped"

elif [ "$checker" == "restart" ]; then

  "$0" stop >& /dev/null
  "$0" start >& /dev/null
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
