#!/usr/bin/env bash
#display the content of the file /etc/passwd
#display username user id home directory path

while IFS= read -r line

do
    echo "$line" | cut -f 1,3,6 -d ':'
done < "/etc/passwd"
