#!/usr/bin/env bash
# Tell the story of passwd


while IFS= read -r line; do
  user_name=$(echo "$line" | cut -d ':' -f1)
  group_id=$(echo "$line" | cut -d ':' -f4)
  home_dir=$(echo "$line" | cut -d ':' -f6)
  comand_shell=$(echo "$line" | cut -d ':' -f7)
  user_id=$(echo "$line" | cut -d ':' -f3)
  pasw=$(echo "$line" | cut -d ':' -f2)
  user_id_info=$(echo "$line" | cut -d ':' -f5)

  echo "The user $user_name is part of the $group_id gang,"\
	  "lives in $home_dir and rides $comand_shell."\
	  "$user_id's place is protected by the passcode $pasw,"\
	  "more info about the user here: $user_id_info"
 done < "/etc/passwd"
