#!/usr/bin/env bash
#4th loop bad luck from China
#9th loop bad luck from japn
#17th loop bad luck from Italy

i=1

while [ $i -le 20 ]
do
	case $i in
	4) echo $i
	      echo "bad luck from China"
	      ;;
	   9) echo $i
	      echo "bad luck from Japan"
	      ;;
	   17) echo $i
	      echo "bad luck from Italy"
	      ;;
	   *) echo $i
	   ;;
	esac
	i=$(( i + 1 ))
done
