#!/usr/bin/env bash
#display the time for 12 hours
#display mint from 1 to 59

hour=0

while [ $hour -le 12 ]

do
    mint=1
    echo "Hour: $hour"
    while [ $mint -le 59 ]
    do
	echo $mint
	mint=$(( mint + 1))
    done
    hour=$(( hour + 1))
done
