#!/usr/bin/env bash
# the nginx user
chmod 644 /etc/nginx/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill -f apache2
sudo -u nginx service nginx restart
